name: Security Vulnerability
description: Report a security vulnerability (for non-sensitive issues only)
title: "[Security]: "
labels: ["security", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT: For sensitive security vulnerabilities, please DO NOT use this form.**

        Instead, email dev@waqasmajeed.dev directly. See our [Security Policy](../../SECURITY.md) for details.

        This form is only for security-related issues that are NOT sensitive (e.g., documentation improvements, security best practices suggestions).

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm this is not a sensitive vulnerability
      options:
        - label: I confirm this is NOT a sensitive security vulnerability that could be exploited
          required: true
        - label: I have read the [Security Policy](../../SECURITY.md)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security concern or improvement
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How can this be improved?
      placeholder: I suggest...
    validations:
      required: false